### ISSUE TITLE
Bulk updates unsuccessful at being shiny - version 2-20160516

### ISSUE THREAD

**Issue by Idealien** [obenland/shiny-updates#110] opened 2016-05-16 19:55 UTC
Doing individual plugin shiny updates for non-core does work from both /wp-admin/update-core.php and /wp-admin/plugins.php, but various attempts at doing bulk were not quite so much.

1. Plugins page - Whether selecting 1 or more to update via bulk, all generate "# failures" note at the top with a "undefined: undefined" detail when I click the link.

1. Bulk updates notice at top w/o scroll only - Scrolled to bottom of plugin list, selected last plugin checkbox and update/apply from bottom of table. No indication that the '1 failure' note was added to the top of plugin page.

1. Core Update - Going from 4.3.1 to 4.5.2. Reports successful, but brings me to the new / about page for 4.4.2.

1. Core Update All - Redirects to /update-core.php?action=do-all-upgrade which has a white-screen-of-death going on, nothing added in error log when in development mode.

**Comment by swissspidy** [comment] 2016-05-18 12:39
Hey there, thanks for your report!

1. Interesting. Are there any errors in your browser's console?
2. Good catch! We definitely should look into improving the UX there.  
 @MichaelArestad @mapk Perhaps you folks have an idea?
3. Thanks for that. The redirect is intended, but it should definitely update to the version stated in the updates table, not an older one. Did it upgrade to 4.5 the second time?
4. The "Update All" functionality on update-core.php has not yet been completed, but I'm working on it. Sorry for that!

**Comment by Idealien** [comment] 2016-05-18 13:33
1. No - Was using firefox .
3. No - multiple attempts kept showing 4.5.2 update available and completing to 4.4.2.

**Comment by swissspidy** [comment] 2016-05-22 11:09
Can't really reproduce the bug with the plugin updates. Perhaps it was fixed by 368d66d9a7ffeb1ce113cfd1b1e31744e4b13863 or it might be the same bug as mentioned in #122.

Updating core and the 'Update All' button now work as intended, so there shouldn't be any problems with that anymore.

Could you give this another try? Thanks!

**Comment by Idealien** [comment] 2016-05-23 16:22
Item #1 is no longer reproduce-able with 05/23 release. Tested where plugin updates successfully and include expected failure cases that are properly noted.

Items #3 and #4 are both successful as well. Slightly unexpected behaviour to get a redirect prompt "This page is asking you to confirm that you want to leave - data you have entered may not be saved" when doing a WP version update compared to the non-shiny-version automatically taking to the new about page. But certainly functional.

Great job!

Only remaining item is #2.

**Comment by swissspidy** [comment] 2016-05-23 18:03
That's great news!

> "This page is asking you to confirm that you want to leave - data you have entered may not be saved"

Sounds like there was still something left in the update queue when the redirect occured. That shouldn't happen though.

I might open new issues for this and 2), since latter is an enhancement.

**Comment by mapk** [comment] 2016-05-25 21:07
If there is a failure and a notification appears at the top (while the user is scrolled to the bottom), the page should scroll back up to the top to present that notification to the user.  I think when there is a fatal error of some sort, it's safe to pull the user's attention to it.

**Closed** 2016-05-30 09:30 UTC
Labels: bug, design
