### ISSUE TITLE
FTP credentials not asked in version 2-20160519

### ISSUE THREAD

**Issue by eri-trabiccolo** [obenland/shiny-updates#122] opened 2016-05-19 12:01 UTC
Scenario:
localhost install, no direct access, FTP credentials requested for each update session.

In the Plugins dashboard page, trying to update a plugin.

Clicking on "Install Update Now" in the "View details" modal no FTP credentials request modal is shown. The update icon spins and the notice says "Updating..." but nothing happens.

The debug.log says:
`
[19-May-2016 11:47:06 UTC] PHP Notice:  Trying to get property of non-object in /xx/wordpress/wp-content/plugins/shiny-updates/src/ajax-actions.php on line 375`

So `$wp_filesystem` is not set, but I think the problem is upstream..

Anyway the update of the same plugin works fine (with the FTP credentials modal shown) when clicking on the "update now" link in the notice just below the respective plugin row.

**Comment by swissspidy** [comment] 2016-05-19 12:31
Hey there,

Thanks for your report! I just added a small change to improve the error handling so there won't be any notice.

Let me now if the [latest version from GitHub](https://github.com/obenland/shiny-updates/archive/master.zip) resolves the issue.

Cheers!

**Comment by eri-trabiccolo** [comment] 2016-05-19 12:36
Hello @swissspidy ,
thanks.
Well the php error isn't shown anymore in the log because of the introduced check, but still the update process doesn't go through as it should, the FTP credentials pop-up isn't shown, that's the major issue I think.. :)

**Comment by eri-trabiccolo** [comment] 2016-05-19 14:12
Ah, I see what happens.
Looks a js issue, when the "View details" modal is open it cannot find the filesystemModal anymore
https://github.com/obenland/shiny-updates/blob/master/src/js/shiny-updates.js#L1343
(as well as the other elements, as they are in the modal "parent" )..

Hope this can help somewhat.. always if I understood anything about that ;)

**Comment by eri-trabiccolo** [comment] 2016-05-20 09:12
FYI with the latest commit(368d66) the FTP update works from the modal in 
wp-admin/plugins.php?plugin_status=all
but not in
wp-admin/plugins.php?plugin_status=upgrade

Sometimes get redirected to the front page, when not the icon spins and nothing happens.

Anyway in both case the FTP credential modal shows up, so maybe I might open a different issue (?)

**Comment by swissspidy** [comment] 2016-05-20 09:33
Thanks for the update! I don't think that needs a separate issue at the moment, as I think we're on the right track.

Looks like it's a similar issue as in 368d66d9a7ffeb1ce113cfd1b1e31744e4b13863, so it's likely just an oversight somewhere. Will try to reproduce it with the latest version.

**Comment by eri-trabiccolo** [comment] 2016-05-20 09:36
Fine, thanks for your feedback!

**Comment by swissspidy** [comment] 2016-05-29 20:53
I added some fixes in #164, like an endless spinner popping up every now and then. Other than that, I couldn't find any issues, for example why it shouldn't work on `wp-admin/plugins.php?plugin_status=upgrade` sometimes.

**Comment by eri-trabiccolo** [comment] 2016-05-29 21:11
@swissspidy 
Yea neither I. Might have been just a case.
I'll try again to see it re-occurs with that branch.
BTW, Just discovered that after the 2 time I enter a wrong password the ftp credential modal closes..
It's a different issue of course, but still related to the same subject .. but if you want I open a new issue.

**Comment by eri-trabiccolo** [comment] 2016-05-29 21:37
Maybe that was the issue, maybe the case was that I put a wrong pw the first time and the second time even if I put the right one the update didn't go through.
Or, most likely as I always forgot to start the ftp server, that the first time my ftp server was off so I got an error then I turned it on but still couldn't update.
Anyway that should be the real issue, I can reproduce it. Second try fails.

**Comment by swissspidy** [comment] 2016-05-29 21:41
> BTW, Just discovered that after the 2 time I enter a wrong password the ftp credential modal closes.. can you reproduce it?

Oh, that's fun. Currently investigating. Nasty bug.

**Comment by eri-trabiccolo** [comment] 2016-05-29 21:54
I haven't noticed before, but weird things happen when trying to update (always with ftp method) from the "Details" modal - like getting redirected to the frontpage - also with the latest wp stable and without shinyupdates plugin active.

**Comment by swissspidy** [comment] 2016-05-29 22:32
Alright, the error handling is now kinda fixed on update-core.php, but that can become ugly. See 6c8ee7b238a772d9f36184a3e5cdb387ed9f214e. In addition to that, no error message was displayed in the modal because of some core changes. See 20f8335be9fa4316e04565bd153cccc219aa90c3.

Basically, the reason is what's already documented in `wp.updates.credentialError`: 

> Not cool that we're depending on response for this data. This would feel more whole in a view all tied together.

Since the method only has the response as information, the success and error callbacks are being removed. We could add something like 6c8ee7b238a772d9f36184a3e5cdb387ed9f214e to every method, but there has to be a better way.

@obenland As I'm not experienced with that part, I'd love your insights here.

**Comment by eri-trabiccolo** [comment] 2016-05-29 22:46
I see.
Well I did a bit of mess reporting this issue, confusing the update link and the update button in the "view details" modal. Sorry.
It's weird that they act differently, but they do act differently in the wp latest stable too.
If I may don't forget the "focus" js issue:
`shiny-updates.js?ver=1464559816:1287 Uncaught TypeError: Cannot read property 'focus' of undefined (fixes/filesystem-credentials-dialog branch)`
Actually I get the same error with the latest wp stable when updating from the "view details" modal.

**Comment by swissspidy** [comment] 2016-05-30 05:08
Ouch, I think I just misread your issue, totally my fault! Now I can see that even with #164 applied I get redirected to the front page of the WordPress site when clicking on "Install Update Now" from inside the modal and then "Proceed" in the filesystem credentials dialog afterwards. And yes, the `focus` error happens as well.

Will have a closer look there.

**Comment by swissspidy** [comment] 2016-05-30 08:25
So the redirect happens because `wp_print_request_filesystem_credentials_modal()` uses the site URL for the URL used in the `<form>` and for some reason the Shiny Updates click handler isn't added properly to the "Proceed" button, resulting in an actual POST request to the front page.

**Comment by eri-trabiccolo** [comment] 2016-05-30 08:44
Actually I noticed that the same happens with the latest wp stable without shiny updates active.
Do you confirm this?

**Comment by swissspidy** [comment] 2016-05-30 08:46
That might be very well the case. There are actually a few bugs around the current shiny updates implementation in core. No need to fix them there when we can fix them here and in an eventual merge.

**Comment by eri-trabiccolo** [comment] 2016-05-30 08:49
Yeah sure, just wanted to highlight that it might be a inherited bug to help you to fix it ;)
I wish you success!

**Comment by swissspidy** [comment] 2016-05-30 09:24
The latest update in #164 seems to fix the `focus()` _and_  the redirection bug.

Looks like only the one bug I mentioned in https://github.com/obenland/shiny-updates/issues/122#issuecomment-222386734 seems to be left open.

**Comment by eri-trabiccolo** [comment] 2016-05-30 20:37
Yeah the update from inside the modal works fine now if you enter the right password. :)

Ah, side note, different issue, I cannot close the ftp credentials dialog with the Cancel button (always from inside the modal). No error in the console.

**Comment by swissspidy** [comment] 2016-06-03 00:12
#164 has now been merged into master and the whole filesystem credentials process works smoothly now. Cannot reproduce the bug with the Cancel button. Closing for now.

Let us know if something is not working using the latest version, ideally in a new issue.

Thanks again for testing!

**Closed by swissspidy** 2016-06-03 00:12 UTC
Labels: bug, help wanted
