### ISSUE TITLE
Infinite "Installing..." from modal window

### ISSUE THREAD

**Issue by nomoreme** [obenland/shiny-updates#125] opened 2016-05-19 19:39 UTC
Hi, I've notice this bug on two WordPress installation (on the same server) with shiny-updates version 2-20160519

Steps:
- Plugin -> add plugin
- choose any plugin (from popular or after a seach)
- open the modal "more info"
- click "install" from the bottom of the modal
- the modal close, the button changes to "installing..." with the rotating arrow forever and never change to the "installed" status
If I go to the installed plugin page, the new plugin is displayed correctly

If I choose to install directly from the button of the plugin card (e not from the modal), the button switch correctly to "installing..." and then to "installed".

I've already check with WP_DEBUG but it don't see any error in the log.

Let me know if you need any more info or any way I can help.

**Comment by swissspidy** [comment] 2016-05-19 21:48
Thanks for your report!

I can reproduce this with plugin installs and updates instantiated from inside the modal.

The problem is that the queue checker calls `wp.updates.updatePlugin` and the like without passing the `success` and `error` callbacks as part of `job.data`.

Previously the update and install methods called the callbacks directly, but we moved these outside.

I guess the best way would be to add set the callbacks inside `wp.updates.queueChecker`.

@obenland What do you think about that?

**Comment by swissspidy** [comment] 2016-05-20 08:37
@nomoreme This bug will be fixed in the next update. Thanks again for reporting it!

**Closed** 2016-05-20 08:37 UTC
Labels: bug

**Comment by nomoreme** [comment] 2016-05-20 11:05
@swissspidy Oh, you're welcome! I'm glad I was able to help! :)
