### ISSUE TITLE
update-core.php Design Revisions

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#116] opened 2016-05-18 22:25 UTC
I've mocked up a few revisions for the update-core.php file.

1. Removed 'Update' button for items that don't require an update.
2. Moved the subhead "Updates Available" into the table header.
3. Added a 'disabled' attribute to the 'Update All' buttons when there is no update necessary.
4. Added more padding around the row avatars and desc text.
5. Moved the Re-install button out of the Update table into it's own box at the bottom.

Thoughts?

![v2](https://cloud.githubusercontent.com/assets/617986/15376888/b4a2a038-1d0c-11e6-8fac-fc3c849abb0a.png)

**Comment by swissspidy** [comment] 2016-05-18 22:30
1. The translations row isn't shown anymore if there's no update. See #115. 
 Will do the same for core, though it's worth noting that for trunk installs there's currently an update button as well. For example, without shiny updates and running 4.6-alpha-37438 (latest nightly), I can click update and will 4.6-alpha-37438 (again). Not sure if that's expected.
2. Already implemented code-wise. See #115.
3. Makes sense.
4. Looks good too.
5. Love it!

**Comment by mapk** [comment] 2016-05-18 22:37
Wow, we should probably design for "no content" now, huh?  I didn't think of that.  Let me put something together. Having a blank table would be a bit awkward.

**Comment by obenland** [comment] 2016-05-18 22:39
How about just a "Everything is up to date." text?

**Comment by mapk** [comment] 2016-05-18 22:40
But it has to LOOK GOOD!!!  :)

**Comment by swissspidy** [comment] 2016-05-18 22:54
FYI, if there are absolutely no updates, the list table currently looks like this:

<img width="1265" alt="screen shot 2016-05-19 at 00 53 01" src="https://cloud.githubusercontent.com/assets/841956/15377456/135a118e-1d5c-11e6-8137-2b93f0e07bcf.png">

The translation thingy was a bug, but since the core row is always displayed, the list table was never empty so far.

**Comment by obenland** [comment] 2016-05-18 22:56
I could live with just the "Last checked on…" message displaying. Maybe prefixed with "Your site is up to date." Show the warning only when there is a core update available.

**Comment by swissspidy** [comment] 2016-05-18 23:00
That warning is currently shown by core's `update-core.php` because I'm running trunk, won't be shown for stable sites. Though we should hide it as well if there's no updated nightly, just like I did now in the list table.

**Comment by mapk** [comment] 2016-05-18 23:09
Maybe we hide the table completely? Thoughts on this?

![v2 - no content](https://cloud.githubusercontent.com/assets/617986/15377750/de6a75f2-1d12-11e6-8bac-43db89c0a94e.png)

**Comment by afragen** [comment] 2016-05-18 23:47
What will this look like for those running trunk?

There always was the option to "Update Now" or "Download nightly build".

**Comment by swissspidy** [comment] 2016-05-19 08:12
1. The download option will most likely go away completely.  
 It's just not that helpful for the majority of users.  
 See also https://core.trac.wordpress.org/ticket/36811
2. If you're running trunk and there's no new nightly build, it will look like the screen above.  
  If there _is_ a new nightly build, you'll see the regular list table with the promoted core update.

**Comment by swissspidy** [comment] 2016-05-19 10:51
I like the first mockup better because of the large images and clear indication that not only core is up to date, but translations are as well.

At the moment WordPress does this as well. When you're not running `en_US` and there are _no translation updates_, it will show the "Your translations are all up to date." message. We should keep it that way (see 66ba0a9ec09d0ca379e38f3c54723967648a5e43 and 21e05b79d1a354f5ce48aacc4ced6294b0a9e2f9).

I also like how the re-install option is in its own box, making the distinction between updates and re-install more clear. Should this be the version we use for user tests?

**Comment by mapk** [comment] 2016-05-19 17:28
So to clarify, @swissspidy, you want to keep the Core and Translations rows always visible in the table, and just display a note that says they're up-to-date?

If we're removing those rows when they are up to date, I think rather than displaying a table with nothing in it, we remove the table completely. The table looks very confusing showing a header and footer that repeat information with a small msg saying it's all up to date.

**Comment by afragen** [comment] 2016-05-19 17:29
> 1. The download option will most likely go away completely.
> It's just not that helpful for the majority of users.
> See also https://core.trac.wordpress.org/ticket/36811
>2.  If you're running trunk and there's no new nightly build, it will look like the screen above.
> If there is a new nightly build, you'll see the regular list table with the promoted core update.

I agree with removing the "download as zip" button. But I think the "Re-install" button should remain. Currently if running trunk there is no re-install button. Automatic updates sometimes aren't. Please consider adding back "Re-install Trunk" if the user is running trunk.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/15403151/7a8013fe-1dac-11e6-9613-7eb453ac1ec8.png)

**Comment by mapk** [comment] 2016-05-19 17:37
@afragen: wouldn't the re-install button apply to whatever version of WordPress you're currently running? Do we need to specify two different re-install buttons?

**Comment by afragen** [comment] 2016-05-19 17:43
@mapk ideally it would. Current behavior if I were to use 'Re-install Now' would re-install 4.5.2 with no way to get back to trunk outside of using the Beta Tester plugin.

Does it make sense for those running trunk to have an additional button to re-install trunk or just add the 'Update' button when trunk is updated. 

As often as trunk is updated having the 'Update' button show if automatic updating isn't working. Is that the current behavior? Also, sometimes I would hit the update button "just to make sure" I was actually up to date.

**Comment by swissspidy** [comment] 2016-05-19 18:31
@afragen Good call, I noticed the same today when I suddenly downgraded my site.

Will show the update button for core again, which essentially does a re-install. See 04a0600fe62cf59e476dbb0cf440bc5629f13f62.

**Comment by obenland** [comment] 2016-05-19 18:31
> I like the first mockup better because of the large images and clear indication that not only core is up to date, but translations are as well.

I'd find it rather confusing if there were items in a table that is titled "Available Updates" when there are no updates available.

I like @mapk's [latest mock](https://github.com/obenland/shiny-updates/issues/116#issuecomment-220184759) up a little better, though I wouldn't even add the notice. I'd expect a notice after an action I performed, but not just when I first open the page.

@afragen: How often do you find yourself re-installing WordPress?

**Comment by afragen** [comment] 2016-05-19 18:38
@obenland honestly I only really do this on trunk if I haven't been on the site for a couple of days. Enough that I appreciate it being there. I'm not sure many people would downgrade from trunk to release so perhaps just a general 'Re-install' button that would re-install trunk for those on trunk and re-install the release version for those on it. Then just a single button.

BTW, I did do this when the Update button was present and it was wicked fast.

**Comment by obenland** [comment] 2016-05-19 18:44
It sounds to me the button is more a beta tester or developer feature rather than something that is really useful to 80% of WordPress users

**Comment by swissspidy** [comment] 2016-05-19 19:19
Here's the comparison of a site running the latest 4.6 nightly build.

**Updates screen without Shiny Updates:**

<img width="1006" alt="screen shot 2016-05-19 at 21 16 00" src="https://cloud.githubusercontent.com/assets/841956/15406537/43fdddc4-1e07-11e6-9a94-d740f5ca099c.png">

* _Update Now_ updates the install, essentially re-installing trunk since it's already running the latest nightly build.
* _Re-install Now_ re-installs 4.5.2

**Updates screen with Shiny Updates:**

<img width="1258" alt="screen shot 2016-05-19 at 21 15 47" src="https://cloud.githubusercontent.com/assets/841956/15406548/4c82dcf6-1e07-11e6-85c1-515c33ba6bbc.png">

* _Update_ is the same as _Update Now_ from above
* _Re-install Now_ is the same as _Re-install Now_ from above

----

IMHO it makes sense to keep both buttons in this case.

**Comment by melchoyce** [comment] 2016-05-19 20:26
Is there any way to drop the bottom table header if there's < 3 (maybe even 5) updates available? It feels a little silly to sandwich one or two, or even no updates between duplicate headers.

**Comment by swissspidy** [comment] 2016-05-19 22:27
I just merged the latest round of improvements into master.

**Comment by BurlesonBrad** [comment] 2016-05-20 13:41
![shiny-updates](https://cloud.githubusercontent.com/assets/6208757/15428841/58256c16-1e63-11e6-979a-eee0afe19ed5.png)

Look, as much as all y'all rocket ninja super coding vagrant gulping grunts dump the var via the CLI _(...and all that fun stuff)_, sometimes the **FINAL RESULT** of all the programming has a horrid user experience.  

To the same extremely talented level that you folks code, I tend to (usually) stay out of my Vagrant setup and focus mainly on **psychology, behavior, and user experience**  

I've been following a lot of core tracs, watching @swissspidy enable people to talk to the search box, understanding code from @obenland 's ajax search, _(perhaps even learning a thing or two)_, and I wanted to just :raised_hands:  **STOP A SECOND** :raised_hands: and say what a great job y'all have done.  This is perfectly laid out to give excellent visual understanding of what's happening, and what needs to be done to keep WordPress updated. 

Out of all the gits I follow, all the tracs I've watched developed, this has been one of the **best**. The whole WordPress community needs the blessing of your Shiny Updates, and this is definitely read to be merged into core ~ **FOREVER!**

**Comment by afragen** [comment] 2016-05-21 04:53
@swissspidy in trunk, 'Update' button give 'Update Failed!' message with Shiny Updates active. With Shiny Updates deactivated, the 'Update Now' works correctly.

**Comment by swissspidy** [comment] 2016-05-22 10:59
@afragen Updating trunk should now work again, see 297225a238d4f827d68a9752f583ae7f541a78d8.

@BurlesonBrad Thank you so much for your feedback!!

**Comment by swissspidy** [comment] 2016-05-22 12:51
So, from what I can see, the only thing left to be done here is the layout for when there is no update available. There were some mockups floating around, but we haven't agreed on a solution yet.

**Comment by afragen** [comment] 2016-05-22 15:34
@swissspidy updating trunk works! It's was a little jarring not to see it redirected to the usual about page, but I understand that wouldn't exactly be shiny.

**Comment by swissspidy** [comment] 2016-05-22 15:37
@afragen It actually should, see 0077617f3490d542e5f49ffea0515c81ce375525… 😁 If not, would you mind opening a new issue?

**Comment by afragen** [comment] 2016-05-22 15:43
#135

**Comment by swissspidy** [comment] 2016-05-29 18:01
Quick update after [our latest discussion](https://wordpress.slack.com/archives/feature-shinyupdates/p1464197160001044):

@mapk shared a mockup he felt pretty strong with:

![no-data](https://cloud.githubusercontent.com/assets/841956/15635145/eb8aba04-25d6-11e6-9517-c9b90257e467.png)

We agreed on changing the wording a bit and not making it a success notice. I played a bit with it and ended up with something I'd like to share with you here.

**Current updates screen**

First of all, without Shiny Updates it looks like this:

<img width="819" alt="screen shot 2016-05-29 at 19 38 02" src="https://cloud.githubusercontent.com/assets/841956/15635171/a871fbbe-25d7-11e6-8e65-77cb2280cd16.png">

**Option A**

This uses an `<h2>` like on the current screen.

<img width="812" alt="screen shot 2016-05-29 at 19 45 03" src="https://cloud.githubusercontent.com/assets/841956/15635174/b81615fa-25d7-11e6-8370-ce071f3ac759.png">

**Option B**

This uses an inline admin notice like in the suggested mockup.

<img width="683" alt="screen shot 2016-05-29 at 19 47 29" src="https://cloud.githubusercontent.com/assets/841956/15635181/d82983d6-25d7-11e6-8788-55ad473f68a9.png">

Note that in all version the second sentence ("Future security updates will be applied automatically.") is only added if automatic updates are supported.

**Pull Request:** Check out #162, which implements option b.

**Comment by afragen** [comment] 2016-05-29 18:04
I like option B

**Comment by swissspidy** [comment] 2016-05-31 13:50
Alright, I just merged option B so we can more easily iterate from there and discuss it in today's dev meeting (again)

**Comment by BurlesonBrad** [comment] 2016-05-31 16:12
I asked a few complete and total newbies _(who haven't got any desire for a github account :wink: )_ to install this and simply shoot me Fb messages on their thoughts.

Reaching w**AAAAAAAAAAAAAAAA**y far to both ends of the spectrum of...
- rocket ninja full stack genius command line superstar, to...
- holy crap why didn't I learn code before I got a family of 5, to...
- ok, Brad, I installed this WooCommerce thing, now what do I click, to...
- _everything in between_

...the _$not-so-official-focus-group_ has definitely responded that the "Core" option is **exponentially** better now that it is **not** being grouped together.

Summation: Habitually, instead of the individual ```Update``` button, they'd click ```Update All``` & then get a bit irritated Akismet and all the default themes were back in their instance.  

### Looks Even Better Now! 
# Great Job!!

**Comment by mapk** [comment] 2016-05-31 20:28
I think we keep the current language of Option B, but just add the green border.

![up-to-date](https://cloud.githubusercontent.com/assets/617986/15689386/8ef9eb30-2733-11e6-8b68-911ac81a082d.png)

**Comment by afragen** [comment] 2016-05-31 20:50
Quick mock of putting 'last checked' and 'Check Again' in box. Will obviously need to remove the in-between line.

![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/15690048/8a2234ca-2736-11e6-82c7-f1c27cc5e96e.png)

**Comment by mapk** [comment] 2016-05-31 20:58
Thanks for the mockup, @afragen, but I think putting everything in boxes starts looking a bit odd.  In a sense the notification is definitely a Success notification because at some point it checked to see if everything was updated and this was the msg it displayed.  And if we click the "Check Again" button, and nothing needs updating, this is the msg displayed.

It's just has more permanence and doesn't go away until you have an update.

**Comment by afragen** [comment] 2016-05-31 21:08
I'm good with the border, just liked the plain box better. 😉

**Comment by swissspidy** [comment] 2016-06-01 05:06
@mapk Without the green checkmark? Because I get it automatically when adding the `notice-success` class to the notice.

**Comment by BurlesonBrad** [comment] 2016-06-01 13:22
Like a bull in a field of heifers, the spinning updater just keeps on going and going and going.

![shiny-updates](https://cloud.githubusercontent.com/assets/6208757/15710647/91c5bfb8-27d0-11e6-8f6e-ab528a6b4272.gif)
I'm always one for pitchin' in :+1: I'll always do my best for finding bugs :beetle: But to determine **_what_** type of bug it is :question: Well, sometimes I come up a bit short :disappointed: 

That consistent "loading" was in: php7, lots-o-cache, CloudFlare, tons-of-WooCommerce, oh _(I just thought of this....)_ and it's running in sites where I've killed off Jason and his resting API thing as well.  When there is a refresh of ```/wp-admin/update-core.php``` all is well.  But the initial click simply left the spinner going on and on.

**How can I contribute to diagnosing _what_ the issue is?**

**Comment by mapk** [comment] 2016-06-01 16:25
@swissspidy I'd hate to create another class that doesn't include the checkmark, but I think it's best without one. We don't have any other css selectors that can do this?

**Comment by obenland** [comment] 2016-06-01 16:41
@swissspidy @mapk This is caused by an overzealous shiny updates CSS selector which should probably be removed entirely.

**Comment by swissspidy** [comment] 2016-06-02 23:26
I added a green border for the notice now and fixed the CSS selector. See 4b2f5858b1f49d3891219d5f7a1a148791f1c733 and 6647e529470f0cb6fcde588584821d70a794218e.

For now this is closed.

**Closed by swissspidy** 2016-06-02 23:26 UTC
Labels: design
