### ISSUE TITLE
JS error in core update page on multisite

### ISSUE THREAD

**Issue by afragen** [obenland/shiny-updates#111] opened 2016-05-17 23:00 UTC
Using a new install of multisite on trunk made with VVV I am unable to update Hello Dolly from the `network/update-core.php`. The only plugins installed are Akismet, Hello Dolly, and Shiny Updates. Only Shiny Updates is active.

When updating the trunk, shiny updates works. When trying to update the plugin I get the following JS error.

TypeError: undefined is not an object (evaluating '$message.attr') line 274 shiny-updates.js

![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/15342223/71852a4c-1c48-11e6-8ad1-cecb8b731e6d.png)

**Comment by swissspidy** [comment] 2016-05-18 12:40
Thanks for letting us now!

Will do some more testing on multisite to fix this annoying bug today or tomorrow!

**Comment by ethitter** [comment] 2016-05-19 04:08
I thought I'd tracked down this issue, but I can't reproduce it reliably. It is limited to plugins, at least in my experience. Even with https://github.com/ethitter/shiny-updates/commit/cd04445b340a64de4bd6ee24faebd9cdd7cc5733, the error returns sometimes. There also doesn't seem to be a correlation between plugins being network-activated or limited to single sites, despite my initial thinking.

**Comment by swissspidy** [comment] 2016-05-19 08:15
Regarding cd04445b340a64de4bd6ee24faebd9cdd7cc5733, `wp.updates.updatePlugin` should actually never be called on the `update-core.php` page.

The JS has changed quite a bit yesterday. On which line is the error happening at the moment?

**Comment by swissspidy** [comment] 2016-05-19 09:54
Ah, the bug is in `wp.updates.queueChecker`.

**Comment by swissspidy** [comment] 2016-05-19 10:41
I implemented a fix in #119

**Comment by swissspidy** [comment] 2016-05-19 11:01
Alright, the error should be fixed now thanks to #119. Can't reproduce it anymore.

**Closed by swissspidy** 2016-05-19 11:01 UTC
Labels: bug, multisite
