### ISSUE TITLE
Don't add the loading icon to the primary button on update-core

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#156] opened 2016-05-25 22:50 UTC
<img width="257" alt="bildschirmfoto 2016-05-26 um 00 47 29" src="https://cloud.githubusercontent.com/assets/617637/15558634/a0ecdf0c-22db-11e6-8178-cabe41147a71.png">

Or it should be at least another color.

**Comment by swissspidy** [comment] 2016-05-26 15:59
Closing as a duplicate of #157

**Closed** 2016-05-26 16:01 UTC
