### ISSUE TITLE
Single plugin update does not work on updates page

### ISSUE THREAD

**Issue by wolly66** [obenland/shiny-updates#121] opened 2016-05-19 11:37 UTC
I've updated a plugin.

As you can see in the screenshot, after plugin is updated, still say updating.

Aggiornato! means updated
Aggiornamento in corso... means updating...

I'm using chrome 51.0.2704.47 beta (64-bit) on mac.
![aggiornamenti_di_wordpress_ _wolly_s_weblog_ _wordpress](https://cloud.githubusercontent.com/assets/1724280/15392335/c5ee7a50-1dc6-11e6-8b09-3f507220d967.jpg)

**Comment by swissspidy** [comment] 2016-05-19 11:58
Hey there,

Thanks for testing the plugin and reporting your issue here! 

This might have been fixed in 8b59bd090015ce91691c56752cf660e30215228d. Would you mind testing the latest version? You can download it here: https://github.com/obenland/shiny-updates/archive/master.zip

Cheers!

**Comment by wolly66** [comment] 2016-05-19 13:11
As I have an update, I'll check

**Comment by swissspidy** [comment] 2016-05-22 08:52
@wolly66 Have you already had the time to test the updated plugin? Would be awesome to hear it's working for you :-)

**Comment by wolly66** [comment] 2016-05-23 10:00
I'm testing now :-)

2 problems:

1) If I click on update on a single plugin, doesn't work at all
2) The shiny updates versione that I downloaded from github is version 2 and nothing else and it ask me to update :-)

**Comment by wolly66** [comment] 2016-05-23 10:01
So, the problem is still there, sorry :-)

**Comment by swissspidy** [comment] 2016-05-23 11:06
1) Still no errors in the console? Do you see any network activity in the developer tools? What happens when you update a single plugin _without_ Shiny Updates, do you need to enter FTP credentials?
2) That's not a bug. Because of the synch to WordPress.org, the version there is higher than the one on GitHub.

**Comment by wolly66** [comment] 2016-05-23 12:55
No, I do not need to enter FTP credentials

**Comment by swissspidy** [comment] 2016-05-31 14:01
Closing in favour of #122. See #164.

**Closed by swissspidy** 2016-05-31 14:01 UTC
Labels: bug, feedback
